"""removed is_active and role col from public.users and added new table: institution+memberhsips

Revision ID: 15a6ac59ee66
Revises: e32076e6947e
Create Date: 2026-08-09 17:01:18.102178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a6ac59ee66'
down_revision: Union[str, Sequence[str], None] = 'e32076e6947e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_role_check'), 'users', type_='check')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), server_default=sa.text("'Analyst'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_check_constraint(op.f('users_role_check'), 'users', "role::text = ANY (ARRAY['Analyst'::character varying, 'Staff'::character varying, 'Faculty'::character varying]::text[])")
    # ### end Alembic commands ###
