"""added lots of new tables

Revision ID: 5be9c6037ac6
Revises: 3660e2095b38
Create Date: 2026-08-09 17:42:18.345026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5be9c6037ac6'
down_revision: Union[str, Sequence[str], None] = '3660e2095b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_terms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('application_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='academic_terms_end_date_check'),
    sa.ForeignKeyConstraint(['institution_id'], ['public.institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code', name='academic_terms_institution_id_code_key'),
    schema='public'
    )
    op.create_table('institution_memberships',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), server_default=sa.text("'Analyst'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('Admin', 'Analyst', 'Staff', 'Faculty')", name='institution_memberships_role_check'),
    sa.ForeignKeyConstraint(['institution_id'], ['public.institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('institution_id', 'user_id'),
    schema='public'
    )
    op.create_table('people',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('preferred_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('lifecycle_stage', sa.String(length=30), server_default=sa.text("'prospect'"), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            lifecycle_stage IN (\n                'prospect',\n                'applicant',\n                'admitted',\n                'committed',\n                'enrolled',\n                'alumni',\n                'inactive'\n            )\n            ", name='people_lifecycle_stage_check'),
    sa.ForeignKeyConstraint(['institution_id'], ['public.institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('institution_id', 'email', name='people_institution_email_key'),
    schema='public'
    )
    op.create_index('people_email_idx', 'people', ['email'], unique=False, schema='public')
    op.create_index('people_external_reference_idx', 'people', ['institution_id', 'external_reference'], unique=True, schema='public', postgresql_where=sa.text('external_reference IS NOT NULL'))
    op.create_index('people_lifecycle_stage_idx', 'people', ['institution_id', 'lifecycle_stage'], unique=False, schema='public')
    op.create_table('programs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('degree_level', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['public.institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code', name='programs_institution_id_code_key'),
    schema='public'
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=True),
    sa.Column('application_year', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=40), server_default=sa.text("'started'"), nullable=False),
    sa.Column('decision_code', sa.String(length=20), nullable=True),
    sa.Column('reply_code', sa.String(length=20), nullable=True),
    sa.Column('applicant_source', sa.String(length=100), nullable=True),
    sa.Column('transfer_institution_type', sa.String(length=40), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            decision_code IS NULL\n            OR decision_code IN (\n                'AC',\n                'AP',\n                'WL',\n                'RH'\n            )\n            ", name='applications_decision_code_check'),
    sa.CheckConstraint("\n            reply_code IS NULL\n            OR reply_code IN (\n                'Y',\n                'DF',\n                'NC',\n                'NS',\n                'NR'\n            )\n            ", name='applications_reply_code_check'),
    sa.CheckConstraint("\n            stage IN (\n                'started',\n                'submitted',\n                'under_review',\n                'admitted',\n                'waitlisted',\n                'denied',\n                'committed',\n                'withdrawn'\n            )\n            ", name='applications_stage_check'),
    sa.CheckConstraint("\n            transfer_institution_type IS NULL\n            OR transfer_institution_type IN (\n                'community_college',\n                'four_year',\n                'international',\n                'other'\n            )\n            ", name='applications_transfer_institution_type_check'),
    sa.ForeignKeyConstraint(['person_id'], ['public.people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['public.programs.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['public.academic_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'program_id', 'application_year', name='applications_person_program_year_key'),
    schema='public'
    )
    op.create_index('applications_program_year_idx', 'applications', ['program_id', 'application_year'], unique=False, schema='public')
    op.create_index('applications_stage_idx', 'applications', ['stage'], unique=False, schema='public')
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=250), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            direction IS NULL\n            OR direction IN (\n                'inbound',\n                'outbound',\n                'internal'\n            )\n            ", name='interactions_direction_check'),
    sa.CheckConstraint("\n            interaction_type IN (\n                'email',\n                'phone',\n                'meeting',\n                'note',\n                'sms',\n                'advising'\n            )\n            ", name='interactions_type_check'),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['public.institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['public.people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('interactions_person_idx', 'interactions', ['person_id', sa.literal_column('occurred_at DESC')], unique=False, schema='public')
    op.create_table('student_profiles',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('student_number', sa.String(length=50), nullable=False),
    sa.Column('entry_term_id', sa.UUID(), nullable=True),
    sa.Column('current_program_id', sa.UUID(), nullable=True),
    sa.Column('student_status', sa.String(length=30), server_default=sa.text("'active'"), nullable=False),
    sa.Column('expected_graduation_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            student_status IN (\n                'active',\n                'leave',\n                'graduated',\n                'withdrawn',\n                'dismissed'\n            )\n            ", name='student_profiles_status_check'),
    sa.ForeignKeyConstraint(['current_program_id'], ['public.programs.id'], ),
    sa.ForeignKeyConstraint(['entry_term_id'], ['public.academic_terms.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['public.people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id'),
    sa.UniqueConstraint('student_number'),
    schema='public'
    )
    op.create_table('student_term_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('credits_attempted', sa.Numeric(precision=6, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('credits_earned', sa.Numeric(precision=6, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('term_gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('cumulative_gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('academic_standing', sa.String(length=30), nullable=True),
    sa.Column('advisor_meetings', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            academic_standing IS NULL\n            OR academic_standing IN (\n                'good',\n                'warning',\n                'probation',\n                'suspension'\n            )\n            ", name='student_term_records_academic_standing_check'),
    sa.CheckConstraint('cumulative_gpa BETWEEN 0 AND 4', name='student_term_records_cumulative_gpa_check'),
    sa.CheckConstraint('term_gpa BETWEEN 0 AND 4', name='student_term_records_term_gpa_check'),
    sa.ForeignKeyConstraint(['person_id'], ['public.people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['public.programs.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['public.academic_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'term_id', name='student_term_records_person_term_key'),
    schema='public'
    )
    op.create_index('student_term_records_gpa_idx', 'student_term_records', ['cumulative_gpa'], unique=False, schema='public')
    op.create_index('student_term_records_term_idx', 'student_term_records', ['term_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('student_term_records_term_idx', table_name='student_term_records', schema='public')
    op.drop_index('student_term_records_gpa_idx', table_name='student_term_records', schema='public')
    op.drop_table('student_term_records', schema='public')
    op.drop_table('student_profiles', schema='public')
    op.drop_index('interactions_person_idx', table_name='interactions', schema='public')
    op.drop_table('interactions', schema='public')
    op.drop_index('applications_stage_idx', table_name='applications', schema='public')
    op.drop_index('applications_program_year_idx', table_name='applications', schema='public')
    op.drop_table('applications', schema='public')
    op.drop_table('programs', schema='public')
    op.drop_index('people_lifecycle_stage_idx', table_name='people', schema='public')
    op.drop_index('people_external_reference_idx', table_name='people', schema='public', postgresql_where=sa.text('external_reference IS NOT NULL'))
    op.drop_index('people_email_idx', table_name='people', schema='public')
    op.drop_table('people', schema='public')
    op.drop_table('institution_memberships', schema='public')
    op.drop_table('academic_terms', schema='public')
    # ### end Alembic commands ###
