"""added role check constraints on the public.uesrs table

Revision ID: 7069760a8548
Revises: b2dcb22c3473
Create Date: 2026-08-09 03:14:40.357741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7069760a8548'
down_revision: Union[str, Sequence[str], None] = 'b2dcb22c3473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('users_role_check', 'users', "role IN ('Analyst', 'Staff', 'Faculty')", schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_role_check', 'users', schema='public', type_='check')
    # ### end Alembic commands ###
