"""added department column in the public.department_memebership table

Revision ID: fbba7765e042
Revises: 9d307bfaaafc
Create Date: 2026-08-13 17:13:06.736577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbba7765e042'
down_revision: Union[str, Sequence[str], None] = '9d307bfaaafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('academic_terms_institution_id_fkey'), 'academic_terms', type_='foreignkey')
    op.create_foreign_key(None, 'academic_terms', 'institutions', ['institution_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('applications_person_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_term_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_program_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'people', ['person_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'academic_terms', ['term_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'applications', 'programs', ['program_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('institution_memberships', sa.Column('department', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('institution_memberships_institution_id_fkey'), 'institution_memberships', type_='foreignkey')
    op.drop_constraint(op.f('institution_memberships_user_id_fkey'), 'institution_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'institution_memberships', 'institutions', ['institution_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'institution_memberships', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('interactions_created_by_fkey'), 'interactions', type_='foreignkey')
    op.drop_constraint(op.f('interactions_institution_id_fkey'), 'interactions', type_='foreignkey')
    op.drop_constraint(op.f('interactions_person_id_fkey'), 'interactions', type_='foreignkey')
    op.create_foreign_key(None, 'interactions', 'people', ['person_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'interactions', 'institutions', ['institution_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'interactions', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('people_institution_id_fkey'), 'people', type_='foreignkey')
    op.create_foreign_key(None, 'people', 'institutions', ['institution_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('programs_institution_id_fkey'), 'programs', type_='foreignkey')
    op.create_foreign_key(None, 'programs', 'institutions', ['institution_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('student_profiles_current_program_id_fkey'), 'student_profiles', type_='foreignkey')
    op.drop_constraint(op.f('student_profiles_entry_term_id_fkey'), 'student_profiles', type_='foreignkey')
    op.drop_constraint(op.f('student_profiles_person_id_fkey'), 'student_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'student_profiles', 'people', ['person_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'student_profiles', 'academic_terms', ['entry_term_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'student_profiles', 'programs', ['current_program_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('student_term_records_term_id_fkey'), 'student_term_records', type_='foreignkey')
    op.drop_constraint(op.f('student_term_records_person_id_fkey'), 'student_term_records', type_='foreignkey')
    op.drop_constraint(op.f('student_term_records_program_id_fkey'), 'student_term_records', type_='foreignkey')
    op.create_foreign_key(None, 'student_term_records', 'programs', ['program_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'student_term_records', 'people', ['person_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'student_term_records', 'academic_terms', ['term_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_term_records', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'student_term_records', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'student_term_records', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('student_term_records_program_id_fkey'), 'student_term_records', 'programs', ['program_id'], ['id'])
    op.create_foreign_key(op.f('student_term_records_person_id_fkey'), 'student_term_records', 'people', ['person_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('student_term_records_term_id_fkey'), 'student_term_records', 'academic_terms', ['term_id'], ['id'])
    op.drop_constraint(None, 'student_profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'student_profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'student_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('student_profiles_person_id_fkey'), 'student_profiles', 'people', ['person_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('student_profiles_entry_term_id_fkey'), 'student_profiles', 'academic_terms', ['entry_term_id'], ['id'])
    op.create_foreign_key(op.f('student_profiles_current_program_id_fkey'), 'student_profiles', 'programs', ['current_program_id'], ['id'])
    op.drop_constraint(None, 'programs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('programs_institution_id_fkey'), 'programs', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'people', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('people_institution_id_fkey'), 'people', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'interactions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'interactions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'interactions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('interactions_person_id_fkey'), 'interactions', 'people', ['person_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('interactions_institution_id_fkey'), 'interactions', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('interactions_created_by_fkey'), 'interactions', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'institution_memberships', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'institution_memberships', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('institution_memberships_user_id_fkey'), 'institution_memberships', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('institution_memberships_institution_id_fkey'), 'institution_memberships', 'institutions', ['institution_id'], ['id'])
    op.drop_column('institution_memberships', 'department')
    op.drop_constraint(None, 'applications', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'applications', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'applications', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('applications_program_id_fkey'), 'applications', 'programs', ['program_id'], ['id'])
    op.create_foreign_key(op.f('applications_term_id_fkey'), 'applications', 'academic_terms', ['term_id'], ['id'])
    op.create_foreign_key(op.f('applications_person_id_fkey'), 'applications', 'people', ['person_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'academic_terms', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('academic_terms_institution_id_fkey'), 'academic_terms', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
